apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ysu49ca6u-go
  janus-idp.io/tekton: ysu49ca6u-go
  backstage.io/kubernetes-id: ysu49ca6u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ysu49ca6u-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
